-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 11:04:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `DescripcionCategoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaisOrigen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaisOrigen` (
  `idPaisOrigen` INT NOT NULL AUTO_INCREMENT,
  `DescripcionPais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaisOrigen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materiales` (
  `idMateriales` INT NOT NULL AUTO_INCREMENT,
  `DescripcionMateriales` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMateriales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `DescripcionEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marcas` (
  `idMarcas` INT NOT NULL AUTO_INCREMENT,
  `DescripcionMarcas` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `idProveedores` INT NOT NULL AUTO_INCREMENT,
  `NombreProveedor` VARCHAR(100) NOT NULL,
  `DireccionProveedor` VARCHAR(100) NOT NULL,
  `TelefonoProveedor` VARCHAR(100) NOT NULL,
  `EmailProveedor` VARCHAR(100) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idProveedores`),
  INDEX `fk_Proveedores_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  INDEX `fk_Proveedores_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedores_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedores_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `DescripcionProducto` VARCHAR(100) NOT NULL,
  `PrecioCompra` INT NOT NULL,
  `PrecioVenta` INT NOT NULL,
  `FechaIngreso` VARCHAR(100) NOT NULL,
  `Talla` VARCHAR(100) NOT NULL,
  `Categorias_idCategorias` INT NOT NULL,
  `PaisOrigen_idPaisOrigen` INT NOT NULL,
  `Materiales_idMateriales` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Marcas_idMarcas` INT NOT NULL,
  `Proveedores_idProveedores` INT NOT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fk_Productos_Categorias1_idx` (`Categorias_idCategorias` ASC) VISIBLE,
  INDEX `fk_Productos_PaisOrigen1_idx` (`PaisOrigen_idPaisOrigen` ASC) VISIBLE,
  INDEX `fk_Productos_Materiales1_idx` (`Materiales_idMateriales` ASC) VISIBLE,
  INDEX `fk_Productos_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  INDEX `fk_Productos_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  INDEX `fk_Productos_Proveedores1_idx` (`Proveedores_idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categorias1`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_PaisOrigen1`
    FOREIGN KEY (`PaisOrigen_idPaisOrigen`)
    REFERENCES `mydb`.`PaisOrigen` (`idPaisOrigen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Materiales1`
    FOREIGN KEY (`Materiales_idMateriales`)
    REFERENCES `mydb`.`Materiales` (`idMateriales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `mydb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `mydb`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `NombreCliente` VARCHAR(100) NOT NULL,
  `ApellidoCliente` VARCHAR(100) NOT NULL,
  `DireccionCliente` VARCHAR(100) NOT NULL,
  `TelefonoCliente` VARCHAR(100) NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `DescripcionTipoDoc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `DescripcionRol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(100) NOT NULL,
  `ApellidoUsuario` VARCHAR(100) NOT NULL,
  `TelefonoUsuario` VARCHAR(100) NOT NULL,
  `EmailUsuario` VARCHAR(100) NOT NULL,
  `NumeroDocumento` VARCHAR(100) NOT NULL,
  `Usuario` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(100) NOT NULL,
  `TipoDocumento_idTipoDocumento` INT NOT NULL,
  `Roles_idRoles` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_TipoDocumento1_idx` (`TipoDocumento_idTipoDocumento` ASC) VISIBLE,
  INDEX `fk_Usuarios_Roles1_idx` (`Roles_idRoles` ASC) VISIBLE,
  INDEX `fk_Usuarios_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_TipoDocumento1`
    FOREIGN KEY (`TipoDocumento_idTipoDocumento`)
    REFERENCES `mydb`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Roles1`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `mydb`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `Fecha` VARCHAR(100) NOT NULL,
  `PrecioFinal` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_Ventas_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Ventas_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Ventas_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
